### ISSUE TITLE
fundoc not working in eXist v5

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/function-documentation#29]
Scenario: Plain eXist-db v5, install fundoc via app manager. access fundoc app:

```
HTTP ERROR 500
Problem accessing /exist/apps/fundocs/. Reason:

    Server Error
Caused by:
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/fundocs/: err:XPST0017 Function xmldb:is-admin-user()  is not defined in module namespace: http://exist-db.org/xquery/xmldb [at line 30, column 48]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/fundocs/: err:XPST0017 Function xmldb:is-admin-user()  is not defined in module namespace: http://exist-db.org/xquery/xmldb [at line 30, column 48]
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:371)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:859)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	... 16 more
Caused by: org.exist.xquery.XPathException: err:XPST0017 Function xmldb:is-admin-user()  is not defined in module namespace: http://exist-db.org/xquery/xmldb [at line 30, column 48]
	at org.exist.xquery.FunctionFactory.getInternalModuleFunction(FunctionFactory.java:294)
	at org.exist.xquery.FunctionFactory.functionCall(FunctionFactory.java:261)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:94)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:55)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:51)
	at org.exist.xquery.parser.XQueryTreeParser.functionCall(XQueryTreeParser.java:11190)
	at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:7776)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3561)
	at org.exist.xquery.parser.XQueryTreeParser.constructor(XQueryTreeParser.java:10695)
	at org.exist.xquery.parser.XQueryTreeParser.constructor(XQueryTreeParser.java:10554)
	at org.exist.xquery.parser.XQueryTreeParser.constructor(XQueryTreeParser.java:10554)
	at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:7564)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3561)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:330)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:833)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:2620)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:423)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:426)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:426)
	at org.exist.xquery.parser.XQueryTreeParser.mainModule(XQueryTreeParser.java:4044)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3987)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3642)
	at org.exist.xquery.XQuery.compile(XQuery.java:128)
	at org.exist.xquery.XQuery.compile(XQuery.java:79)
	at org.exist.xquery.XQuery.compile(XQuery.java:71)
	at org.exist.http.urlrewrite.XQueryURLRewrite.runQuery(XQueryURLRewrite.java:669)
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:243)
	... 34 more
Caused by:
javax.servlet.ServletException: An error occurred while processing request to /exist/apps/fundocs/: err:XPST0017 Function xmldb:is-admin-user()  is not defined in module namespace: http://exist-db.org/xquery/xmldb [at line 30, column 48]
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:371)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:859)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.exist.xquery.XPathException: err:XPST0017 Function xmldb:is-admin-user()  is not defined in module namespace: http://exist-db.org/xquery/xmldb [at line 30, column 48]
	at org.exist.xquery.FunctionFactory.getInternalModuleFunction(FunctionFactory.java:294)
	at org.exist.xquery.FunctionFactory.functionCall(FunctionFactory.java:261)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:94)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:55)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:51)
	at org.exist.xquery.parser.XQueryTreeParser.functionCall(XQueryTreeParser.java:11190)
	at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:7776)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3561)
	at org.exist.xquery.parser.XQueryTreeParser.constructor(XQueryTreeParser.java:10695)
	at org.exist.xquery.parser.XQueryTreeParser.constructor(XQueryTreeParser.java:10554)
	at org.exist.xquery.parser.XQueryTreeParser.constructor(XQueryTreeParser.java:10554)
	at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:7564)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3561)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:330)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:833)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:2620)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:423)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:426)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:426)
	at org.exist.xquery.parser.XQueryTreeParser.mainModule(XQueryTreeParser.java:4044)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3987)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3642)
	at org.exist.xquery.XQuery.compile(XQuery.java:128)
	at org.exist.xquery.XQuery.compile(XQuery.java:79)
	at org.exist.xquery.XQuery.compile(XQuery.java:71)
	at org.exist.http.urlrewrite.XQueryURLRewrite.runQuery(XQueryURLRewrite.java:669)
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:243)
	... 34 more
Caused by:
org.exist.xquery.XPathException: err:XPST0017 Function xmldb:is-admin-user()  is not defined in module namespace: http://exist-db.org/xquery/xmldb [at line 30, column 48]
	at org.exist.xquery.FunctionFactory.getInternalModuleFunction(FunctionFactory.java:294)
	at org.exist.xquery.FunctionFactory.functionCall(FunctionFactory.java:261)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:94)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:55)
	at org.exist.xquery.FunctionFactory.createFunction(FunctionFactory.java:51)
	at org.exist.xquery.parser.XQueryTreeParser.functionCall(XQueryTreeParser.java:11190)
	at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:7776)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3561)
	at org.exist.xquery.parser.XQueryTreeParser.constructor(XQueryTreeParser.java:10695)
	at org.exist.xquery.parser.XQueryTreeParser.constructor(XQueryTreeParser.java:10554)
	at org.exist.xquery.parser.XQueryTreeParser.constructor(XQueryTreeParser.java:10554)
	at org.exist.xquery.parser.XQueryTreeParser.primaryExpr(XQueryTreeParser.java:7564)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:3561)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:330)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:833)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:2620)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:423)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:426)
	at org.exist.xquery.parser.XQueryTreeParser.expr(XQueryTreeParser.java:426)
	at org.exist.xquery.parser.XQueryTreeParser.mainModule(XQueryTreeParser.java:4044)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3987)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3642)
	at org.exist.xquery.XQuery.compile(XQuery.java:128)
	at org.exist.xquery.XQuery.compile(XQuery.java:79)
	at org.exist.xquery.XQuery.compile(XQuery.java:71)
	at org.exist.http.urlrewrite.XQueryURLRewrite.runQuery(XQueryURLRewrite.java:669)
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:243)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:859)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by joewiz** [comment]
No errors here with function-documentation v1.1.1 and current eXist-db develop branch. @craigberry's audit script also returns no hits for `xmldb:is-admin-user`, nor does a search of the source.

Could you confirm you're still experiencing an issue and review versions, etc.?

**Comment by joewiz** [comment]
Yeah, I think this issue should've been closed with https://github.com/eXist-db/function-documentation/pull/30.

**Comment by dizzzz** [comment]
works perfect
